// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: orderbook.proto
#ifndef GRPC_orderbook_2eproto__INCLUDED
#define GRPC_orderbook_2eproto__INCLUDED

#include "orderbook.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace orderbook {

// OrderBook service definition
class OrderBookService final {
 public:
  static constexpr char const* service_full_name() {
    return "orderbook.OrderBookService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Get orderbook data for a specific symbol
    virtual ::grpc::Status GetOrderBook(::grpc::ClientContext* context, const ::orderbook::OrderBookRequest& request, ::orderbook::OrderBookResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::orderbook::OrderBookResponse>> AsyncGetOrderBook(::grpc::ClientContext* context, const ::orderbook::OrderBookRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::orderbook::OrderBookResponse>>(AsyncGetOrderBookRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::orderbook::OrderBookResponse>> PrepareAsyncGetOrderBook(::grpc::ClientContext* context, const ::orderbook::OrderBookRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::orderbook::OrderBookResponse>>(PrepareAsyncGetOrderBookRaw(context, request, cq));
    }
    // Get list of available symbols
    virtual ::grpc::Status GetAvailableSymbols(::grpc::ClientContext* context, const ::orderbook::Empty& request, ::orderbook::SymbolsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::orderbook::SymbolsResponse>> AsyncGetAvailableSymbols(::grpc::ClientContext* context, const ::orderbook::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::orderbook::SymbolsResponse>>(AsyncGetAvailableSymbolsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::orderbook::SymbolsResponse>> PrepareAsyncGetAvailableSymbols(::grpc::ClientContext* context, const ::orderbook::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::orderbook::SymbolsResponse>>(PrepareAsyncGetAvailableSymbolsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Get orderbook data for a specific symbol
      virtual void GetOrderBook(::grpc::ClientContext* context, const ::orderbook::OrderBookRequest* request, ::orderbook::OrderBookResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetOrderBook(::grpc::ClientContext* context, const ::orderbook::OrderBookRequest* request, ::orderbook::OrderBookResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Get list of available symbols
      virtual void GetAvailableSymbols(::grpc::ClientContext* context, const ::orderbook::Empty* request, ::orderbook::SymbolsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetAvailableSymbols(::grpc::ClientContext* context, const ::orderbook::Empty* request, ::orderbook::SymbolsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::orderbook::OrderBookResponse>* AsyncGetOrderBookRaw(::grpc::ClientContext* context, const ::orderbook::OrderBookRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::orderbook::OrderBookResponse>* PrepareAsyncGetOrderBookRaw(::grpc::ClientContext* context, const ::orderbook::OrderBookRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::orderbook::SymbolsResponse>* AsyncGetAvailableSymbolsRaw(::grpc::ClientContext* context, const ::orderbook::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::orderbook::SymbolsResponse>* PrepareAsyncGetAvailableSymbolsRaw(::grpc::ClientContext* context, const ::orderbook::Empty& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetOrderBook(::grpc::ClientContext* context, const ::orderbook::OrderBookRequest& request, ::orderbook::OrderBookResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::orderbook::OrderBookResponse>> AsyncGetOrderBook(::grpc::ClientContext* context, const ::orderbook::OrderBookRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::orderbook::OrderBookResponse>>(AsyncGetOrderBookRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::orderbook::OrderBookResponse>> PrepareAsyncGetOrderBook(::grpc::ClientContext* context, const ::orderbook::OrderBookRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::orderbook::OrderBookResponse>>(PrepareAsyncGetOrderBookRaw(context, request, cq));
    }
    ::grpc::Status GetAvailableSymbols(::grpc::ClientContext* context, const ::orderbook::Empty& request, ::orderbook::SymbolsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::orderbook::SymbolsResponse>> AsyncGetAvailableSymbols(::grpc::ClientContext* context, const ::orderbook::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::orderbook::SymbolsResponse>>(AsyncGetAvailableSymbolsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::orderbook::SymbolsResponse>> PrepareAsyncGetAvailableSymbols(::grpc::ClientContext* context, const ::orderbook::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::orderbook::SymbolsResponse>>(PrepareAsyncGetAvailableSymbolsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetOrderBook(::grpc::ClientContext* context, const ::orderbook::OrderBookRequest* request, ::orderbook::OrderBookResponse* response, std::function<void(::grpc::Status)>) override;
      void GetOrderBook(::grpc::ClientContext* context, const ::orderbook::OrderBookRequest* request, ::orderbook::OrderBookResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetAvailableSymbols(::grpc::ClientContext* context, const ::orderbook::Empty* request, ::orderbook::SymbolsResponse* response, std::function<void(::grpc::Status)>) override;
      void GetAvailableSymbols(::grpc::ClientContext* context, const ::orderbook::Empty* request, ::orderbook::SymbolsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::orderbook::OrderBookResponse>* AsyncGetOrderBookRaw(::grpc::ClientContext* context, const ::orderbook::OrderBookRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::orderbook::OrderBookResponse>* PrepareAsyncGetOrderBookRaw(::grpc::ClientContext* context, const ::orderbook::OrderBookRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::orderbook::SymbolsResponse>* AsyncGetAvailableSymbolsRaw(::grpc::ClientContext* context, const ::orderbook::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::orderbook::SymbolsResponse>* PrepareAsyncGetAvailableSymbolsRaw(::grpc::ClientContext* context, const ::orderbook::Empty& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetOrderBook_;
    const ::grpc::internal::RpcMethod rpcmethod_GetAvailableSymbols_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Get orderbook data for a specific symbol
    virtual ::grpc::Status GetOrderBook(::grpc::ServerContext* context, const ::orderbook::OrderBookRequest* request, ::orderbook::OrderBookResponse* response);
    // Get list of available symbols
    virtual ::grpc::Status GetAvailableSymbols(::grpc::ServerContext* context, const ::orderbook::Empty* request, ::orderbook::SymbolsResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetOrderBook : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetOrderBook() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetOrderBook() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetOrderBook(::grpc::ServerContext* /*context*/, const ::orderbook::OrderBookRequest* /*request*/, ::orderbook::OrderBookResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetOrderBook(::grpc::ServerContext* context, ::orderbook::OrderBookRequest* request, ::grpc::ServerAsyncResponseWriter< ::orderbook::OrderBookResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetAvailableSymbols : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetAvailableSymbols() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetAvailableSymbols() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAvailableSymbols(::grpc::ServerContext* /*context*/, const ::orderbook::Empty* /*request*/, ::orderbook::SymbolsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetAvailableSymbols(::grpc::ServerContext* context, ::orderbook::Empty* request, ::grpc::ServerAsyncResponseWriter< ::orderbook::SymbolsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetOrderBook<WithAsyncMethod_GetAvailableSymbols<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetOrderBook : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetOrderBook() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::orderbook::OrderBookRequest, ::orderbook::OrderBookResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::orderbook::OrderBookRequest* request, ::orderbook::OrderBookResponse* response) { return this->GetOrderBook(context, request, response); }));}
    void SetMessageAllocatorFor_GetOrderBook(
        ::grpc::MessageAllocator< ::orderbook::OrderBookRequest, ::orderbook::OrderBookResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::orderbook::OrderBookRequest, ::orderbook::OrderBookResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetOrderBook() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetOrderBook(::grpc::ServerContext* /*context*/, const ::orderbook::OrderBookRequest* /*request*/, ::orderbook::OrderBookResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetOrderBook(
      ::grpc::CallbackServerContext* /*context*/, const ::orderbook::OrderBookRequest* /*request*/, ::orderbook::OrderBookResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetAvailableSymbols : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetAvailableSymbols() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::orderbook::Empty, ::orderbook::SymbolsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::orderbook::Empty* request, ::orderbook::SymbolsResponse* response) { return this->GetAvailableSymbols(context, request, response); }));}
    void SetMessageAllocatorFor_GetAvailableSymbols(
        ::grpc::MessageAllocator< ::orderbook::Empty, ::orderbook::SymbolsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::orderbook::Empty, ::orderbook::SymbolsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetAvailableSymbols() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAvailableSymbols(::grpc::ServerContext* /*context*/, const ::orderbook::Empty* /*request*/, ::orderbook::SymbolsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetAvailableSymbols(
      ::grpc::CallbackServerContext* /*context*/, const ::orderbook::Empty* /*request*/, ::orderbook::SymbolsResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetOrderBook<WithCallbackMethod_GetAvailableSymbols<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetOrderBook : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetOrderBook() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetOrderBook() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetOrderBook(::grpc::ServerContext* /*context*/, const ::orderbook::OrderBookRequest* /*request*/, ::orderbook::OrderBookResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetAvailableSymbols : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetAvailableSymbols() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetAvailableSymbols() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAvailableSymbols(::grpc::ServerContext* /*context*/, const ::orderbook::Empty* /*request*/, ::orderbook::SymbolsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetOrderBook : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetOrderBook() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetOrderBook() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetOrderBook(::grpc::ServerContext* /*context*/, const ::orderbook::OrderBookRequest* /*request*/, ::orderbook::OrderBookResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetOrderBook(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetAvailableSymbols : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetAvailableSymbols() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetAvailableSymbols() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAvailableSymbols(::grpc::ServerContext* /*context*/, const ::orderbook::Empty* /*request*/, ::orderbook::SymbolsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetAvailableSymbols(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetOrderBook : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetOrderBook() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetOrderBook(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetOrderBook() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetOrderBook(::grpc::ServerContext* /*context*/, const ::orderbook::OrderBookRequest* /*request*/, ::orderbook::OrderBookResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetOrderBook(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetAvailableSymbols : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetAvailableSymbols() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetAvailableSymbols(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetAvailableSymbols() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAvailableSymbols(::grpc::ServerContext* /*context*/, const ::orderbook::Empty* /*request*/, ::orderbook::SymbolsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetAvailableSymbols(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetOrderBook : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetOrderBook() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::orderbook::OrderBookRequest, ::orderbook::OrderBookResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::orderbook::OrderBookRequest, ::orderbook::OrderBookResponse>* streamer) {
                       return this->StreamedGetOrderBook(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetOrderBook() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetOrderBook(::grpc::ServerContext* /*context*/, const ::orderbook::OrderBookRequest* /*request*/, ::orderbook::OrderBookResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetOrderBook(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::orderbook::OrderBookRequest,::orderbook::OrderBookResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetAvailableSymbols : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetAvailableSymbols() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::orderbook::Empty, ::orderbook::SymbolsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::orderbook::Empty, ::orderbook::SymbolsResponse>* streamer) {
                       return this->StreamedGetAvailableSymbols(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetAvailableSymbols() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetAvailableSymbols(::grpc::ServerContext* /*context*/, const ::orderbook::Empty* /*request*/, ::orderbook::SymbolsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetAvailableSymbols(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::orderbook::Empty,::orderbook::SymbolsResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetOrderBook<WithStreamedUnaryMethod_GetAvailableSymbols<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetOrderBook<WithStreamedUnaryMethod_GetAvailableSymbols<Service > > StreamedService;
};

}  // namespace orderbook


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_orderbook_2eproto__INCLUDED
